{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgresql.primary.initdb.scriptsConfigMap }}
  namespace: {{ .Release.Namespace }}
data:
  01-init-db-user.sh: |
    postgresql_create_portal_user() {
      local -r escaped_password="${PORTAL_PASSWORD//\'/\'\'}"
      info "Creating user portal"
      export PGPASSWORD="$POSTGRES_PASSWORD"
      echo "CREATE USER portal WITH PASSWORD '${escaped_password}';" | psql -U postgres
    }
    postgresql_create_portal_user
    postgresql_create_provisioning_user() {
      local -r escaped_password="${PROVISIONING_PASSWORD//\'/\'\'}"
      info "Creating user provisioning"
      export PGPASSWORD="$POSTGRES_PASSWORD"
      echo "CREATE USER provisioning WITH PASSWORD '${escaped_password}';" | psql -U postgres
    }
    postgresql_create_provisioning_user
  02-init-db.sql: |
    CREATE SCHEMA portal;
    ALTER SCHEMA portal OWNER TO portal;
    CREATE SCHEMA provisioning;
    ALTER SCHEMA provisioning OWNER TO provisioning;
    CREATE TABLE public.__efmigrations_history_portal (
        migration_id character varying(150) NOT NULL,
        product_version character varying(32) NOT NULL
    );
    ALTER TABLE public.__efmigrations_history_portal OWNER TO portal;
    CREATE TABLE public.__efmigrations_history_provisioning (
        migration_id character varying(150) NOT NULL,
        product_version character varying(32) NOT NULL
    );
    ALTER TABLE public.__efmigrations_history_provisioning OWNER TO provisioning;
{{- end -}}
