###############################################################
# Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.administration.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.administration.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.administration.name }}
    spec:
      containers:
      - name: {{ .Values.backend.administration.name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.backend.administration.image.name }}:{{ .Values.backend.administration.image.administrationservicetag | default .Chart.AppVersion }}"
        imagePullPolicy: "Always"
        ports:
        - containerPort: {{ .Values.portContainer }}
        env:
        - name: "Checklist__Bpdm__BaseAddress"
          value: "test"
        - name: "Checklist__Bpdm__ClientId"
          value: "test"
        - name: "Checklist__Bpdm__ClientSecret"
          value: "test"
        - name: "Checklist__Bpdm__GrantType"
          value: "test"
        - name: "Checklist__Bpdm__KeycloakTokenAddress"
          value: "test"
        - name: "Checklist__Bpdm__Password"
          value: "test"
        - name: "Checklist__Bpdm__Scope"
          value: "test"
        - name: "Checklist__Bpdm__Username"
          value: "test"
        - name: "Checklist__Clearinghouse__BaseAddress"
          value: "test"
        - name: "Checklist__Clearinghouse__ClientId"
          value: "test"
        - name: "Checklist__Clearinghouse__ClientSecret"
          value: "test"
        - name: "Checklist__Clearinghouse__GrantType"
          value: "test"
        - name: "Checklist__Clearinghouse__KeycloakTokenAddress"
          value: "test"
        - name: "Checklist__Clearinghouse__Password"
          value: "test"
        - name: "Checklist__Clearinghouse__Scope"
          value: "test"
        - name: "Checklist__Clearinghouse__Username"
          value: "test"
        - name: "Checklist__Custodian__BaseAddress"
          value: "test"
        - name: "Checklist__Custodian__ClientId"
          value: "test"
        - name: "Checklist__Custodian__ClientSecret"
          value: "test"
        - name: "Checklist__Custodian__GrantType"
          value: "test"
        - name: "Checklist__Custodian__KeycloakTokenAddress"
          value: "test"
        - name: "Checklist__Custodian__Password"
          value: "test"
        - name: "Checklist__Custodian__Scope"
          value: "openid"
        - name: "Checklist__Custodian__Username"
          value: "test"
        - name: "Checklist__SdFactory__ClientId"
          value: "test"
        - name: "Checklist__SdFactory__ClientSecret"
          value: "test"
        - name: "Checklist__SdFactory__GrantType"
          value: "test"
        - name: "Checklist__SdFactory__KeycloakTokenAddress"
          value: "test"
        - name: "Checklist__SdFactory__Password"
          value: "test"
        - name: "Checklist__SdFactory__Scope"
          value: "test"
        - name: "Checklist__SdFactory__SdFactoryIssuerBpn"
          value: "test"
        - name: "Checklist__SdFactory__SdFactoryUrl"
          value: "test"
        - name: "Checklist__SdFactory__Username"
          value: "test"
        - name: "ConnectionStrings__PortalDB"
          value: "test"
        - name: "ConnectionStrings__ProvisioningDB"
          value: "test"
        - name: "Connectors__ValidCertificationContentTypes__0"
          value: "test0"
        - name: "Connectors__ValidCertificationContentTypes__1"
          value: "test1"
        - name: "Connectors__ValidCertificationContentTypes__2"
          value: "test2"
        - name: "Connectors__ValidCertificationContentTypes__3"
          value: "test3"
        - name: "Daps__ClientId"
          value: "test"
        - name: "Daps__ClientSecret"
          value: "test"
        - name: "Daps__DapsUrl"
          value: "test"
        - name: "Daps__GrantType"
          value: "test"
        - name: "Daps__KeycloakTokenAddress"
          value: "test"
        - name: "Daps__Password"
          value: "test"
        - name: "Daps__Scope"
          value: "test"
        - name: "Daps__Username"
          value: "test"
        - name: "DatabaseAccess__Keycloak__ConnectionString"
          value: "test"
        - name: "DatabaseAccess__Keycloak__DatabaseSchema"
          value: "test"
        - name: "DatabaseAccess__Portal__ConnectionString"
          value: "test"
        - name: "DatabaseAccess__Portal__DatabaseSchema"
          value: "test"
        - name: "DebugEnabled"
          value: "True"
        - name: "Document__EnableSeedEndpoint"
          value: "True"
        - name: "IdentityProviderAdmin__CSVSettings__Charset"
          value: "test"
        - name: "IdentityProviderAdmin__CSVSettings__ContentType"
          value: "test"
        - name: "IdentityProviderAdmin__CSVSettings__FileName"
          value: "test"
        - name: "IdentityProviderAdmin__CSVSettings__HeaderEmail"
          value: "test"
        - name: "IdentityProviderAdmin__CSVSettings__HeaderFirstName"
          value: "test"
        - name: "IdentityProviderAdmin__CSVSettings__HeaderLastName"
          value: "test"
        - name: "IdentityProviderAdmin__CSVSettings__HeaderProviderAlias"
          value: "test"
        - name: "IdentityProviderAdmin__CSVSettings__HeaderProviderUserId"
          value: "test"
        - name: "IdentityProviderAdmin__CSVSettings__HeaderProviderUserName"
          value: "test"
        - name: "IdentityProviderAdmin__CSVSettings__HeaderUserId"
          value: "test"
        - name: "IdentityProviderAdmin__CSVSettings__Separator"
          value: ","
        - name: "Invitation__InvitedUserInitialRoles__Cl1-CX-Registration__0"
          value: "test"
        - name: "Invitation__RegistrationAppAddress"
          value: "test"
        - name: "JwtBearerOptions__MetadataAddress"
          value: "test"
        - name: "JwtBearerOptions__TokenValidationParameters__ValidAudience"
          value: "test"
        - name: "JwtBearerOptions__TokenValidationParameters__ValidIssuer"
          value: "test"
        - name: "Keycloak__central__AuthRealm"
          value: "test"
        - name: "Keycloak__central__ClientId"
          value: "test"
        - name: "Keycloak__central__ClientSecret"
          value: "test"
        - name: "Keycloak__central__ConnectionString"
          value: "test"
        - name: "Keycloak__shared__AuthRealm"
          value: "test"
        - name: "Keycloak__shared__ClientId"
          value: "test"
        - name: "Keycloak__shared__ClientSecret"
          value: "test"
        - name: "Keycloak__shared__ConnectionString"
          value: "test"
        - name: "Logging__LogLevel__Org.CatenaX.Ng.Portal.Backend.Administration.Service.BusinessLogic"
          value: "test"
        - name: "Logging__LogLevel__Org.Eclipse.TractusX.Portal.Backend.Bpdm.Library"
          value: "test"
        - name: "Logging__LogLevel__Org.Eclipse.TractusX.Portal.Backend.Custodian.Library"
          value: "test"
        - name: "MailingService__Mail__SmtpHost"
          value: "test"
        - name: "MailingService__Mail__SmtpPassword"
          value: "test"
        - name: "MailingService__Mail__SmtpPort"
          value: "587"
        - name: "MailingService__Mail__SmtpUser"
          value: "test"
        - name: "Provisioning__CentralIdentityProvider__config__clientId"
          value: "test"
        - name: "Provisioning__CentralRealm"
          value: "test"
        - name: "Provisioning__CentralRealmId"
          value: "test"
        - name: "Provisioning__InvitedUserInitialRoles__Cl1-CX-Registration__0"
          value: "test"
        - name: "Provisioning__SharedRealm__smtpServer__auth"
          value: "test"
        - name: "Provisioning__SharedRealm__smtpServer__from"
          value: "test"
        - name: "Provisioning__SharedRealm__smtpServer__host"
          value: "test"
        - name: "Provisioning__SharedRealm__smtpServer__password"
          value: "test"
        - name: "Provisioning__SharedRealm__smtpServer__port"
          value: "test"
        - name: "Provisioning__SharedRealm__smtpServer__replyTo"
          value: "test"
        - name: "Provisioning__SharedRealm__smtpServer__ssl"
          value: "test"
        - name: "Provisioning__SharedRealm__smtpServer__starttls"
          value: "test"
        - name: "Provisioning__SharedRealm__smtpServer__user"
          value: "test"
        - name: "Provisioning__SharedRealmClient__clientId"
          value: "test"
        - name: "Registration__DocumentTypeIds__0"
          value: "test"
        - name: "Registration__PartnerUserInitialRoles__Cl1-CX-Registration__0"
          value: "test"
        - name: "ServiceAccount__ClientId"
          value: "test"
        - name: "SwaggerEnabled"
          value: "True"
        - name: "UserManagement__CompanyUserStatusIds__0"
          value: "test0"
        - name: "UserManagement__CompanyUserStatusIds__1"
          value: "test1"
        - name: "UserManagement__Portal__BasePortalAddress"
          value: "test"
        - name: "UserManagement__Portal__KeycloakClientID"
          value: "test"
