###############################################################
# Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.registration.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.registration.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.registration.name }}
    spec:
      containers:
      - name: {{ .Values.backend.registration.name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.backend.registration.image.name }}:{{ .Values.backend.registration.image.registrationservicetag | default .Chart.AppVersion }}"
        imagePullPolicy: "Always"
        ports:
        - containerPort: {{ .Values.portContainer }}
        env:
        - name: "BPN_ADDRESS"
          value: "{{ .Values.backend.registration.bpnAddress }}"
        - name: "PORTAL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.postgresql.auth.existingSecret }}"
              key: "portal-password"
        - name: "PROVISIONING_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.postgresql.auth.existingSecret }}"
              key: "provisioning-password"
        - name: "CONNECTIONSTRINGS__PORTALDB"
          value: "Server={{ .Values.postgresql.fullnameOverride }}-primary;Database={{ .Values.postgresql.auth.database }};Port={{ .Values.backend.dbConnection.port }};User Id={{ .Values.postgresql.auth.portalUser }};Password=$(PORTAL_PASSWORD);Ssl Mode={{ .Values.backend.dbConnection.sslMode }};"
        - name: "CONNECTIONSTRINGS__PROVISIONINGDB"
          value: "Server={{ .Values.postgresql.fullnameOverride }}-primary;Database={{ .Values.postgresql.auth.database }};Port={{ .Values.backend.dbConnection.port }};User Id={{ .Values.postgresql.auth.provisioningUser }};Password=$(PROVISIONING_PASSWORD);Ssl Mode={{ .Values.backend.dbConnection.sslMode }};"
        - name: "DATABASEACCESS__PORTAL__CONNECTIONSTRING"
          value: "Server={{ .Values.postgresql.fullnameOverride }}-primary;Database={{ .Values.postgresql.auth.database }};Port={{ .Values.backend.dbConnection.port }};User Id={{ .Values.postgresql.auth.portalUser }};Password=$(PORTAL_PASSWORD);Ssl Mode={{ .Values.backend.dbConnection.sslMode }};"
        - name: "DATABASEACCESS__PORTAL__DATABASESCHEMA"
          value: "{{ .Values.backend.dbConnection.schema }}"
        - name: "JWTBEAREROPTIONS__METADATAADDRESS"
          value: "{{ .Values.backend.keycloak.central.jwtBearerOptions.metadataAddress }}"
        - name: "JWTBEAREROPTIONS__TOKENVALIDATIONPARAMETERS__VALIDAUDIENCE"
          value: "{{ .Values.backend.keycloak.central.jwtBearerOptions.tokenValidationParameters.validAudienceRegistration }}"
        - name: "JWTBEAREROPTIONS__TOKENVALIDATIONPARAMETERS__VALIDISSUER"
          value: "{{ .Values.backend.keycloak.central.jwtBearerOptions.tokenValidationParameters.validIssuer }}"
        - name: "KEYCLOAK__CENTRAL__AUTHREALM"
          value: "{{ .Values.backend.keycloak.central.authRealm }}"
        - name: "KEYCLOAK__CENTRAL__CLIENTID"
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.backend.keycloak.secret }}"
              key: "central-client-id"
        - name: "KEYCLOAK__CENTRAL__CLIENTSECRET"
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.backend.keycloak.secret }}"
              key: "central-client-secret"
        - name: "KEYCLOAK__CENTRAL__CONNECTIONSTRING"
          value: "{{ .Values.backend.keycloak.central.baseAddress }}"
        - name: "KEYCLOAK__SHARED__AUTHREALM"
          value: "{{ .Values.backend.keycloak.shared.authRealm }}"
        - name: "KEYCLOAK__SHARED__CLIENTID"
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.backend.keycloak.secret }}"
              key: "shared-client-id"
        - name: "KEYCLOAK__SHARED__CLIENTSECRET"
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.backend.keycloak.secret }}"
              key: "shared-client-secret"
        - name: "KEYCLOAK__SHARED__CONNECTIONSTRING"
          value: "{{ .Values.backend.keycloak.shared.baseAddress }}"
        - name: "LOGGING__LOGLEVEL__ORG.CATENAX.NG.PORTAL.BACKEND.REGISTRATION.SERVICE.BPN"
          value: "{{ .Values.backend.registration.logging.registrationServiceBpn }}"
        - name: "MAILINGSERVICE__MAIL__SMTPHOST"
          value: "{{ .Values.backend.mailing.host }}"
        - name: "MAILINGSERVICE__MAIL__SMTPPASSWORD"
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.backend.mailing.secret }}"
              key: "password"
        - name: "MAILINGSERVICE__MAIL__SMTPPORT"
          value: "{{ .Values.backend.mailing.port }}"
        - name: "MAILINGSERVICE__MAIL__SMTPUSER"
          value: "{{ .Values.backend.mailing.user }}"
        - name: "PROVISIONING__CENTRALREALM"
          value: "{{ .Values.backend.provisioning.centralRealm }}"
        - name: "PROVISIONING__INVITEDUSERINITIALROLES__Cl1-CX-Registration__0"
          value: "{{ .Values.backend.provisioning.invitedUserInitialRoles.registration }}"
        - name: "PROVISIONING__SERVICEACCOUNTCLIENTPREFIX"
          value: "{{ .Values.backend.provisioning.serviceAccountClientPrefix }}"
        - name: "REGISTRATION__APPLICATIONSTATUSIDS__0"
          value: "{{ .Values.backend.registration.applicationStatusIds.status0 }}"
        - name: "REGISTRATION__APPLICATIONSTATUSIDS__1"
          value: "{{ .Values.backend.registration.applicationStatusIds.status1 }}"
        - name: "REGISTRATION__APPLICATIONSTATUSIDS__2"
          value: "{{ .Values.backend.registration.applicationStatusIds.status2 }}"
        - name: "REGISTRATION__BASEPORTALADDRESS"
          value: "{{ .Values.backend.registration.basePortalAddress }}"
        - name: "REGISTRATION__DOCUMENTTYPEIDS__0"
          value: "{{ .Values.backend.registration.documentTypeIds.type0 }}"
        - name: "REGISTRATION__DOCUMENTTYPEIDS__1"
          value: "{{ .Values.backend.registration.documentTypeIds.type1 }}"
        - name: "REGISTRATION__KEYCLOAKCLIENTID"
          value: "{{ .Values.backend.registration.keycloakClientId }}"
        - name: "SWAGGERENABLED"
          value: "{{ .Values.backend.registration.swaggerEnabled }}"
