###############################################################
# Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.mailing.secret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  host: {{ .Values.backend.mailing.host }}
  port: {{ .Values.backend.mailing.port }}
  user: {{ .Values.backend.mailing.user }}
  password: {{ .Values.backend.mailing.password | default ( randAlphaNum 32 | quote ) }}
  provisioning-sharedrealm-host: {{ .Values.backend.provisioning.sharedRealm.smtpServer.host }}
  provisioning-sharedrealm-port: {{ .Values.backend.provisioning.sharedRealm.smtpServer.port }}
  provisioning-sharedrealm-user: {{ .Values.backend.provisioning.sharedRealm.smtpServer.user }}
  provisioning-sharedrealm-password: {{ .Values.backend.provisioning.sharedRealm.smtpServer.password | default ( randAlphaNum 32 | quote ) }}
  provisioning-sharedrealm-from: {{ .Values.backend.provisioning.sharedRealm.smtpServer.from }}
  provisioning-sharedrealm-replyto: {{ .Values.backend.provisioning.sharedRealm.smtpServer.replyTo }}
