{{- if not .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalDatabase.secret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
# use lookup function to check if secret exists
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.externalDatabase.secret) }}
{{ if $secret -}}
data:
  # if secret exists, use value provided from values file (to cover update scenario) or existing value from secret
  # use data map instead of stringData to prevent base64 encoding of already base64-encoded existing value from secret
  # use index function for secret keys with hyphen otherwise '$secret.data.secretKey' works too
  portal-password: {{ ( .Values.externalDatabase.portalPassword | b64enc ) | default ( index $secret.data "portal-password" ) }}
  provisioning-password: {{ ( .Values.externalDatabase.provisioningPassword | b64enc ) | default ( index $secret.data "provisioning-password" ) }}
{{ else -}}
stringData:
  # if secret doesn't exist, use provided value from values file or generate a random one
  portal-password: {{ .Values.externalDatabase.portalPassword | default ( randAlphaNum 32 | quote ) }}
  provisioning-password: {{ .Values.externalDatabase.provisioningPassword | default ( randAlphaNum 32 | quote ) }}
{{ end }}
{{- end -}}
