{{- if not .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalDatabase.secret}}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  portal-password: {{ .Values.externalDatabase.portalUser | default ( randAlphaNum 32 | quote ) }}
  provisioning-password: {{ .Values.externalDatabase.provisioningUser | default ( randAlphaNum 32 | quote ) }}
{{- end -}}
