{{- if .Values.pgadmin4.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: secret-pgadmin4
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.pgadmin4.secret.password }}
{{- end -}}
