###############################################################
# Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

portalAddress: "https://portal-rc.dev.demo.catena-x.net"
portalBackendAddress: "https://portal-backend-rc.dev.demo.catena-x.net"
centralidpAddress: "https://centralidp.dev.demo.catena-x.net"
sharedidpAddress: "https://sharedidp.dev.demo.catena-x.net"
semanticsAddress: "https://semantics.dev.demo.catena-x.net"
dapsAddress: "https://drs.dev.demo.catena-x.net"
bpdmPartnersPoolAddress: "https://partners-pool.dev.demo.catena-x.net"
bpdmPortalGateAddress: "https://portal-gate.dev.demo.catena-x.net"
custodianAddress: "https://managed-identity-wallets.dev.demo.catena-x.net"
sdfactoryAddress: "https://sdfactory.dev.demo.catena-x.net"
clearinghouseAddress: "https://validation.dev.dih-cloud.com"
clearinghouseTokenAddress: "https://iam.dev.dih-cloud.com/realms/notarisation/protocol/openid-connect/token"

frontend:

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: "/$1"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.dev.demo.catena-x.net"
    tls:
      - secretName: "tls-secret"
        hosts:
          - "portal-rc.dev.demo.catena-x.net"
    hosts:
      - host: "portal-rc.dev.demo.catena-x.net"
        paths:
          - path: "/(.*)"
            pathType: "Prefix"
            backend:
              service: "portal"
              port: 8080
          - path: "/registration/(.*)"
            pathType: "Prefix"
            backend:
              service: "registration"
              port: 8080
          - path: "/((assets|documentation)/.*)"
            pathType: "Prefix"
            backend:
              service: "assets"
              port: 8080

  portal:
    image:
      portaltag: 71f0ce6c85aa17ed1926559120ffe5871666bfa7

  assets:
    image:
      assetstag: c25e9a5a8ddae7d87ab1d9c4194efe93929d0d4c

  registration:
    image:
      registrationtag: b9c409d1c44684e50f2517f868d71585fc661f91

backend:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "8m"
      nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.dev.demo.catena-x.net"
    tls:
      - secretName: "tls-secret"
        hosts:
          - "portal-backend-rc.dev.demo.catena-x.net"
    hosts:
      - host: "portal-backend-rc.dev.demo.catena-x.net"
        paths:
          - path: "/api/registration"
            pathType: "Prefix"
            backend:
              service: "registration-service"
              port: 8080
          - path: "/api/administration"
            pathType: "Prefix"
            backend:
              service: "administration-service"
              port: 8080
          - path: "/api/notification"
            pathType: "Prefix"
            backend:
              service: "notification-service"
              port: 8080
          - path: "/api/provisioning"
            pathType: "Prefix"
            backend:
              service: "provisioning-service"
              port: 8080
          - path: "/api/apps"
            pathType: "Prefix"
            backend:
              service: "marketplace-app-service"
              port: 8080
          - path: "/api/services"
            pathType: "Prefix"
            backend:
              service: "services-service"
              port: 8080

  keycloak:
    central:
      clientId: "<path:portal/data/keycloak#central-client-id>"
      clientSecret: "<path:portal/data/dev/keycloak#central-client-secret>"
      dbConnection:
        password: "<path:portal/data/dev/keycloak#central-db-password>"
    shared:
      clientId: "<path:portal/data/keycloak#shared-client-id>"
      clientSecret: "<path:portal/data/dev/keycloak#shared-client-secret>"

  mailing:
    host: "<path:portal/data/mailing#host>"
    port: "<path:portal/data/mailing#port>"
    user: "<path:portal/data/mailing#user>"
    password: "<path:portal/data/mailing#password>"

  registration:
    image:
      registrationservicetag: f85b253a09b707c30efc89fd58db74a69c4c55a0
    logging:
      registrationServiceBpn: "Debug"
    healthChecks:
      startup:
        tags:
        - name: "HEALTHCHECKS__0__TAGS__0"
          value: "keycloak"
        - name: "HEALTHCHECKS__0__TAGS__1"
          value: "portaldb"
    swaggerEnabled: true

  administration:
    image:
      administrationservicetag: f85b253a09b707c30efc89fd58db74a69c4c55a0
    logging:
      businessLogic: "Debug"
      sdfactoryLibrary: "Debug"
    daps:
      clientId: "<path:portal/data/administration#daps-client-id>"
      clientSecret: "<path:portal/data/dev/administration#daps-client-secret>"
    healthChecks:
      startup:
        tags:
        - name: "HEALTHCHECKS__0__TAGS__0"
          value: "keycloak"
        - name: "HEALTHCHECKS__0__TAGS__1"
          value: "portaldb"
        - name: "HEALTHCHECKS__0__TAGS__2"
          value: "provisioningdb"
    swaggerEnabled: true

  provisioning:
    sharedRealm:
      smtpServer:
        host: "<path:portal/data/mailing#host>"
        port: "<path:portal/data/mailing#port>"
        user: "<path:portal/data/mailing#user>"
        password: "<path:portal/data/mailing#password>"
        from: "<path:portal/data/mailing#from>"
        replyTo: "<path:portal/data/mailing#replyto>"
    service:
      image:
        provisioningservicetag: f85b253a09b707c30efc89fd58db74a69c4c55a0
      healthChecks:
        startup:
          tags:
          - name: "HEALTHCHECKS__0__TAGS__0"
            value: "keycloak"
          - name: "HEALTHCHECKS__0__TAGS__1"
            value: "provisioningdb"
      swaggerEnabled: true

  appmarketplace:
    image:
      appmarketplaceservicetag: f85b253a09b707c30efc89fd58db74a69c4c55a0
    logging:
      offersLibrary: "Debug"
    healthChecks:
      startup:
        tags:
        - name: "HEALTHCHECKS__0__TAGS__0"
          value: "keycloak"
        - name: "HEALTHCHECKS__0__TAGS__1"
          value: "portaldb"
    swaggerEnabled: true

  portalmigrations:
    image:
      portalmigrationstag: f85b253a09b707c30efc89fd58db74a69c4c55a0
    seeding:
      testDataEnvironments: "consortia"

  portalmaintenance:
    image:
      portalmaintenancetag: f85b253a09b707c30efc89fd58db74a69c4c55a0

  notification:
    image:
      notificationservicetag: f85b253a09b707c30efc89fd58db74a69c4c55a0
    healthChecks:
      startup:
        tags:
        - name: "HEALTHCHECKS__0__TAGS__0"
          value: "keycloak"
        - name: "HEALTHCHECKS__0__TAGS__1"
          value: "portaldb"
    swaggerEnabled: true

  services:
    image:
      servicesservicetag: f85b253a09b707c30efc89fd58db74a69c4c55a0
    logging:
      offersLibrary: "Debug"
    healthChecks:
      startup:
        tags:
        - name: "HEALTHCHECKS__0__TAGS__0"
          value: "keycloak"
        - name: "HEALTHCHECKS__0__TAGS__1"
          value: "portaldb"
    swaggerEnabled: true

  provisioningmigrations:
    image:
      provisioningmigrationstag: f85b253a09b707c30efc89fd58db74a69c4c55a0

  processesworker:
    image:
      processesworkertag: f85b253a09b707c30efc89fd58db74a69c4c55a0
    logging:
      checklistLibrary: "Debug"
      bpdmLibrary: "Debug"
      clearinghouseLibrary: "Debug"
      custodianLibrary: "Debug"
      sdfactoryLibrary: "Debug"
    bpdm:
      clientId: "<path:portal/data/processes-worker#bpdm-client-id>"
      clientSecret: "<path:portal/data/dev/processes-worker#bpdm-client-secret>"
    clearinghouse:
      clientId: "<path:portal/data/processes-worker#clearinghouse-client-id>"
      clientSecret: "<path:portal/data/dev/processes-worker#clearinghouse-client-secret>"
    custodian:
      clientId: "<path:portal/data/processes-worker#custodian-client-id>"
      clientSecret: "<path:portal/data/dev/processes-worker#custodian-client-secret>"
    sdfactory:
      issuerBpn: "BPNL00000003CRHK"
      clientId: "<path:portal/data/processes-worker#sdfactory-client-id>"
      clientSecret: "<path:portal/data/dev/processes-worker#sdfactory-client-secret>"

postgresql:
  fullnameOverride: "portal-backend-rc-postgresql"
  auth:
    password: "<path:portal/data/dev/postgres#postgres-password>"
    replicationPassword: "<path:portal/data/dev/postgres#replication-password>"
    portalPassword: "<path:portal/data/dev/postgres#portal-password>"
    provisioningPassword: "<path:portal/data/dev/postgres#provisioning-password>"
