###############################################################
# Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

frontend:

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: "/$1"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.pre-prod.demo.catena-x.net"
    tls:
      - secretName: "tls-secret"
        hosts:
          - "portal.pre-prod.demo.catena-x.net"
    hosts:
      - host: "portal.pre-prod.demo.catena-x.net"
        paths:
          - path: "/(.*)"
            pathType: "Prefix"
            backend:
              service: "portal"
              port: 8080
          - path: "/registration/(.*)"
            pathType: "Prefix"
            backend:
              service: "registration"
              port: 8080
          - path: "/((assets|documentation)/.*)"
            pathType: "Prefix"
            backend:
              service: "assets"
              port: 8080

  portal:
    image:
      portaltag: 1.0.0-RC5

  assets:
    image:
      assetstag: 1.0.0-RC3

  registration:
    image:
      registrationtag: 1.0.0-RC2

  env:
    PORTAL_ASSETS_URL: "https://portal.pre-prod.demo.catena-x.net/assets"
    PORTAL_BACKEND_URL: "https://portal-backend.pre-prod.demo.catena-x.net"
    CENTRALIDP_URL: "https://centralidp.pre-prod.demo.catena-x.net/auth"
    BPDM_API_URL: "https://partners-pool.pre-prod.demo.catena-x.net/api"
    SEMANTICS_URL: "https://semantics.pre-prod.demo.catena-x.net"

backend:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "8m"
      nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.pre-prod.demo.catena-x.net"
    tls:
      - secretName: "tls-secret"
        hosts:
          - "portal-backend.pre-prod.demo.catena-x.net"
    hosts:
      - host: "portal-backend.pre-prod.demo.catena-x.net"
        paths:
          - path: "/api/registration"
            pathType: "Prefix"
            backend:
              service: "registration-service"
              port: 8080
          - path: "/api/administration"
            pathType: "Prefix"
            backend:
              service: "administration-service"
              port: 8080
          - path: "/api/notification"
            pathType: "Prefix"
            backend:
              service: "notification-service"
              port: 8080
          - path: "/api/provisioning"
            pathType: "Prefix"
            backend:
              service: "provisioning-service"
              port: 8080
          - path: "/api/apps"
            pathType: "Prefix"
            backend:
              service: "marketplace-app-service"
              port: 8080
          - path: "/api/services"
            pathType: "Prefix"
            backend:
              service: "services-service"
              port: 8080

  basePortalAddress: "https://portal.pre-prod.demo.catena-x.net/home"

  keycloak:
    central:
      baseAddress: "https://centralidp.pre-prod.demo.catena-x.net"
      clientId: "<path:portal/data/keycloak#central-client-id>"
      clientSecret: "<path:portal/data/pre-prod/keycloak#central-client-secret>"
    shared:
      baseAddress: "https://sharedidp.pre-prod.demo.catena-x.net"
      clientId: "<path:portal/data/keycloak#shared-client-id>"
      clientSecret: "<path:portal/data/pre-prod/keycloak#shared-client-secret>"

  mailing:
    host: "<path:portal/data/mailing#host>"
    port: "<path:portal/data/mailing#port>"
    user: "<path:portal/data/mailing#user>"
    password: "<path:portal/data/mailing#password>"

  registration:
    image:
      registrationservicetag: v1.0.0-RC5
    secret:
      appsettings: "<path:portal/data/pre-prod/registration#appsettings.json>"

  administration:
    image:
      administrationservicetag: v1.0.0-RC5
    secret:
      appsettings: "<path:portal/data/pre-prod/administration#appsettings.json>"

  provisioning:
    sharedRealm:
      smtpServer:
        host: "<path:portal/data/mailing#host>"
        port: "<path:portal/data/mailing#port>"
        user: "<path:portal/data/mailing#user>"
        password: "<path:portal/data/mailing#password>"
        from: "<path:portal/data/mailing#from>"
        replyTo: "<path:portal/data/mailing#replyto>"
    service:
      image:
        provisioningservicetag: v1.0.0-RC5
      secret:
        appsettings: "<path:portal/data/pre-prod/provisioning#appsettings.json>"

  appmarketplace:
    image:
      appmarketplaceservicetag: v1.0.0-RC5
    secret:
      appsettings: "<path:portal/data/pre-prod/appmarketplace#appsettings.json>"

  portalmigrations:
    image:
      portalmigrationstag: v1.0.0-RC5
    seeding:
      testDataEnvironments: "consortia"

  portalmaintenance:
    image:
      portalmaintenancetag: v1.0.0-RC5
    secret:
      appsettings: "<path:portal/data/pre-prod/portal-maintenance#appsettings.json>"

  notification:
    image:
      notificationservicetag: v1.0.0-RC5
    secret:
      appsettings: "<path:portal/data/pre-prod/notification#appsettings.json>"

  services:
    image:
      servicesservicetag: v1.0.0-RC5
    secret:
      appsettings: "<path:portal/data/pre-prod/services#appsettings.json>"

  provisioningmigrations:
    image:
      provisioningmigrationstag: v1.0.0-RC5
  
  checklistworker:
    image:
      checklistworkertag: v1.0.0-RC5
    logging:
      checklistLibrary: "Debug"
      bpdmLibrary: "Debug"
      clearinghouseLibrary: "Debug"
      custodianLibrary: "Debug"
      sdfactoryLibrary: "Debug"
    bpdm:
      baseAddress: "https://portal-gate.pre-prod.demo.catena-x.net/"
      tokenAddress: "https://centralidp.pre-prod.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
      clientId: "<path:portal/data/checklist-worker#bpdm-client-id>"
      clientSecret: "<path:portal/data/pre-prod/checklist-worker#bpdm-client-secret>"
    clearinghouse:
      baseAddress: "https://validation.pre-prod.dih-cloud.com/api/v1"
      tokenAddress: "https://centralidp.pre-prod.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
      clientId: "<path:portal/data/checklist-worker#clearinghouse-client-id>"
      clientSecret: "<path:portal/data/pre-prod/checklist-worker#clearinghouse-client-secret>"
    custodian:
      baseAddress: "https://managed-identity-wallets.pre-prod.demo.catena-x.net"
      tokenAddress: "https://centralidp.pre-prod.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
      clientId: "<path:portal/data/checklist-worker#custodian-client-id>"
      clientSecret: "<path:portal/data/pre-prod/checklist-worker#custodian-client-secret>"
    sdfactory:
      baseAddress: "https://sdfactory.pre-prod.demo.catena-x.net/selfdescription"
      tokenAddress: "https://centralidp.pre-prod.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
      issuerBpn: "BPNL00000003CRHK"
      clientId: "<path:portal/data/checklist-worker#sdfactory-client-id>"
      clientSecret: "<path:portal/data/pre-prod/checklist-worker#sdfactory-client-secret>"

postgresql:
  secret:
    password: "<path:portal/data/pre-prod/postgres#postgres-password>"
    replicationPassword: "<path:portal/data/pre-prod/postgres#replication-password>"
    portalPassword: "<path:portal/data/pre-prod/postgres#portal-password>"
    provisioningPassword: "<path:portal/data/pre-prod/postgres#provisioning-password>"

pgadmin4:
  enabled: true
  secret:
    password: "<path:portal/data/pre-prod/pgadmin4#password>"
  env:
    email: portal@catena-x.net
  existingSecret: secret-pgadmin4
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: portal-pgadmin4.pre-prod.demo.catena-x.net
        paths:
        - path: /
          pathType: Prefix
    tls:
      - hosts:
        - portal-pgadmin4.pre-prod.demo.catena-x.net
        secretName: tls-secret
