###############################################################
# Copyright (c) 2021,2022 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

frontend:

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: "/$1"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.dev.demo.catena-x.net"
    tls: 
      - secretName: "tls-secret"
        hosts:
          - "portal.dev.demo.catena-x.net"
    hosts:
      - host: "portal.dev.demo.catena-x.net"
        paths:
          - path: "/(.*)"
            pathType: "Prefix"
            backend:
              service: "portal"
              port: 8080
          - path: "/registration/(.*)"
            pathType: "Prefix"
            backend:
              service: "registration"
              port: 8080
          - path: "/((assets|swagger)/.*)"
            pathType: "Prefix"
            backend:
              service: "assets"
              port: 8080

  portal:
    image:
      portaltag: dev_da813da4060eb45e95d7364159a9db2909e3ef44

  assets:
    image:
      assetstag: main_b7fac569dab96cda8dc9c088bc87b63647ac5854

  registration:
    image:
      registrationtag: dev_2becb1356a972ff8598bd13f001fa3392365ffb2

backend:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "8m"
      nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.dev.demo.catena-x.net"
    tls: 
      - secretName: "tls-secret"
        hosts:
          - "portal-backend.dev.demo.catena-x.net"
    hosts:
      - host: "portal-backend.dev.demo.catena-x.net"
        paths:
          - path: "/api/registration"
            pathType: "Prefix"
            backend:
              service: "registration-service"
              port: 8080
          - path: "/api/administration"
            pathType: "Prefix"
            backend:
              service: "administration-service"
              port: 8080
          - path: "/api/notification"
            pathType: "Prefix"
            backend:
              service: "notification-service"
              port: 8080
          - path: "/api/provisioning"
            pathType: "Prefix"
            backend:
              service: "provisioning-service"
              port: 8080
          - path: "/api/apps"
            pathType: "Prefix"
            backend:
              service: "marketplace-app-service"
              port: 8080
          - path: "/api/services"
            pathType: "Prefix"
            backend:
              service: "services-service"
              port: 8080

  registration:
    image:
      registrationservicetag: 19f5f895b2109b6f82d87b76775d506e65451c34
    secret:
      appsettings: "<path:portal/data/dev/registration#appsettings.json>"

  administration:
    image:
      administrationservicetag: b310fda28d882c6155590dda62192e03d7895ae3
    secret:
      appsettings: "<path:portal/data/dev/administration#appsettings.json>"

  provisioning:
    image:
      provisioningservicetag: a2b9277b48d403c69db9ec728043236bdfc92081
    secret:
      appsettings: "<path:portal/data/dev/provisioning#appsettings.json>"

  appmarketplace:
    image:
      appmarketplaceservicetag: 19f5f895b2109b6f82d87b76775d506e65451c34
    secret:
      appsettings: "<path:portal/data/dev/appmarketplace#appsettings.json>"

  portalmigrations:
    image:
      portalmigrationstag: 19f5f895b2109b6f82d87b76775d506e65451c34
    secret:
      appsettings: "<path:portal/data/dev/portal-migrations#appsettings.json>"

  portalmaintenance:
    image:
      portalmaintenancetag: 19f5f895b2109b6f82d87b76775d506e65451c34
    secret:
      appsettings: "<path:portal/data/dev/portal-maintenance#appsettings.json>"

  notification:
    image:
      notificationservicetag: 19f5f895b2109b6f82d87b76775d506e65451c34
    secret:
      appsettings: "<path:portal/data/dev/notification#appsettings.json>"

  services:
    image:
      servicesservicetag: 19f5f895b2109b6f82d87b76775d506e65451c34
    secret:
      appsettings: "<path:portal/data/dev/services#appsettings.json>"

  provisioningmigrations:
    image:
      provisioningmigrationstag: b310fda28d882c6155590dda62192e03d7895ae3
    secret:
      appsettings: "<path:portal/data/dev/provisioning-migrations#appsettings.json>"

postgresql:
  secret:
    password: "<path:portal/data/dev/postgres#postgres-password>"
    replicationPassword: "<path:portal/data/dev/postgres#replication-password>"
    initUserDbSql: "<path:portal/data/dev/postgres-db-user#01-init-user-db.sql>"

pgadmin4:
  enabled: true
  secret:
    password: "<path:portal/data/dev/pgadmin4#password>"
  env:
    email: portal@catena-x.net
  existingSecret: secret-pgadmin4
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: portal-pgadmin4.dev.demo.catena-x.net
        paths:
        - path: /
          pathType: Prefix
    tls:
      - hosts:
        - portal-pgadmin4.dev.demo.catena-x.net
        secretName: tls-secret
