###############################################################
# Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

frontend:

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: "/$1"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.dev.demo.catena-x.net"
    tls:
      - secretName: "tls-secret"
        hosts:
          - "portal.dev.demo.catena-x.net"
    hosts:
      - host: "portal.dev.demo.catena-x.net"
        paths:
          - path: "/(.*)"
            pathType: "Prefix"
            backend:
              service: "portal"
              port: 8080
          - path: "/registration/(.*)"
            pathType: "Prefix"
            backend:
              service: "registration"
              port: 8080
          - path: "/((assets|documentation)/.*)"
            pathType: "Prefix"
            backend:
              service: "assets"
              port: 8080

  portal:
    image:
      portaltag: main_7194d84a7bbfb8e187d7c588833759d06bab3f30

  assets:
    image:
      assetstag: main_fa6dca83b7a3e344a10f368d0988ee1ea93bc37b

  registration:
    image:
      registrationtag: main_c13fd5ac5ef8eaccf1ba88ba3c7f10a3be715cab

  env:
    PORTAL_ASSETS_URL: "https://portal.dev.demo.catena-x.net/assets"
    PORTAL_BACKEND_URL: "https://portal-backend.dev.demo.catena-x.net"
    CENTRALIDP_URL: "https://centralidp.dev.demo.catena-x.net/auth"
    BPDM_API_URL: "https://partners-pool.dev.demo.catena-x.net/api"
    SEMANTICS_URL: "https://semantics.dev.demo.catena-x.net"

backend:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "8m"
      nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.dev.demo.catena-x.net"
    tls:
      - secretName: "tls-secret"
        hosts:
          - "portal-backend.dev.demo.catena-x.net"
    hosts:
      - host: "portal-backend.dev.demo.catena-x.net"
        paths:
          - path: "/api/registration"
            pathType: "Prefix"
            backend:
              service: "registration-service"
              port: 8080
          - path: "/api/administration"
            pathType: "Prefix"
            backend:
              service: "administration-service"
              port: 8080
          - path: "/api/notification"
            pathType: "Prefix"
            backend:
              service: "notification-service"
              port: 8080
          - path: "/api/provisioning"
            pathType: "Prefix"
            backend:
              service: "provisioning-service"
              port: 8080
          - path: "/api/apps"
            pathType: "Prefix"
            backend:
              service: "marketplace-app-service"
              port: 8080
          - path: "/api/services"
            pathType: "Prefix"
            backend:
              service: "services-service"
              port: 8080

  basePortalAddress: "https://portal.dev.demo.catena-x.net/home"

  keycloak:
    central:
      baseAddress: "https://centralidp.dev.demo.catena-x.net"
      clientId: "<path:portal/data/keycloak#central-client-id>"
      clientSecret: "<path:portal/data/dev/keycloak#central-client-secret>"
      jwtBearerOptions:
        metadataAddress: "https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/.well-known/openid-configuration"
        tokenValidationParameters:
          validIssuer: "https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central"
      dbConnection:
        password: "<path:portal/data/dev/keycloak#central-db-password>"
    shared:
      baseAddress: "https://sharedidp.dev.demo.catena-x.net"
      clientId: "<path:portal/data/keycloak#shared-client-id>"
      clientSecret: "<path:portal/data/dev/keycloak#shared-client-secret>"

  mailing:
    host: "<path:portal/data/mailing#host>"
    port: "<path:portal/data/mailing#port>"
    user: "<path:portal/data/mailing#user>"
    password: "<path:portal/data/mailing#password>"

  registration:
    image:
      registrationservicetag: 695e8d4774c40425a48c11a0a4ddbf73da6c73b8
    secret:
      appsettings: "<path:portal/data/dev/registration#appsettings.json>"

  administration:
    image:
      administrationservicetag: eccf1f31dc864e83151776eabe73f2e2765afd2f
    secret:
      appsettings: "<path:portal/data/dev/administration#appsettings.json>"

  provisioning:
    sharedRealm:
      smtpServer:
        host: "<path:portal/data/mailing#host>"
        port: "<path:portal/data/mailing#port>"
        user: "<path:portal/data/mailing#user>"
        password: "<path:portal/data/mailing#password>"
        from: "<path:portal/data/mailing#from>"
        replyTo: "<path:portal/data/mailing#replyto>"
    service:
      image:
        provisioningservicetag: 695e8d4774c40425a48c11a0a4ddbf73da6c73b8
      debugEnabled: true
      swaggerEnabled: true

  appmarketplace:
    image:
      appmarketplaceservicetag: 695e8d4774c40425a48c11a0a4ddbf73da6c73b8
    logging:
      offersLibrary: "Debug"
    appOverviewAddress: "https://portal.dev.demo.catena-x.net/appoverview"
    debugEnabled: true
    swaggerEnabled: true

  portalmigrations:
    image:
      portalmigrationstag: 695e8d4774c40425a48c11a0a4ddbf73da6c73b8
    seeding:
      testDataEnvironments: "consortia"

  portalmaintenance:
    image:
      portalmaintenancetag: 695e8d4774c40425a48c11a0a4ddbf73da6c73b8

  notification:
    image:
      notificationservicetag: eccf1f31dc864e83151776eabe73f2e2765afd2f
    debugEnabled: true
    swaggerEnabled: true

  services:
    name: "services-service"
    image:
      servicesservicetag: eccf1f31dc864e83151776eabe73f2e2765afd2f
    logging:
      offersLibrary: "Debug"
    serviceMarketplaceAddress: "https://portal.dev.demo.catena-x.net/servicemarketplace"
    debugEnabled: true
    swaggerEnabled: true

  provisioningmigrations:
    image:
      provisioningmigrationstag: 695e8d4774c40425a48c11a0a4ddbf73da6c73b8

  checklistworker:
    image:
      checklistworkertag: 695e8d4774c40425a48c11a0a4ddbf73da6c73b8
    logging:
      checklistLibrary: "Debug"
      bpdmLibrary: "Debug"
      clearinghouseLibrary: "Debug"
      custodianLibrary: "Debug"
      sdfactoryLibrary: "Debug"
    bpdm:
      baseAddress: "https://portal-gate.dev.demo.catena-x.net/"
      tokenAddress: "https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
      clientId: "<path:portal/data/checklist-worker#bpdm-client-id>"
      clientSecret: "<path:portal/data/dev/checklist-worker#bpdm-client-secret>"
    clearinghouse:
      baseAddress: "https://validation.dev.dih-cloud.com"
      tokenAddress: "https://keycloak-dev.dih-cloud.com/realms/notarisation/protocol/openid-connect/token"
      clientId: "<path:portal/data/checklist-worker#clearinghouse-client-id>"
      clientSecret: "<path:portal/data/dev/checklist-worker#clearinghouse-client-secret>"
    custodian:
      baseAddress: "https://managed-identity-wallets.dev.demo.catena-x.net"
      tokenAddress: "https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
      clientId: "<path:portal/data/checklist-worker#custodian-client-id>"
      clientSecret: "<path:portal/data/dev/checklist-worker#custodian-client-secret>"
    sdfactory:
      baseAddress: "https://sdfactory.dev.demo.catena-x.net/selfdescription"
      tokenAddress: "https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
      issuerBpn: "BPNL00000003CRHK"
      clientId: "<path:portal/data/checklist-worker#sdfactory-client-id>"
      clientSecret: "<path:portal/data/dev/checklist-worker#sdfactory-client-secret>"

postgresql:
  auth:
    password: "<path:portal/data/dev/postgres#postgres-password>"
    replicationPassword: "<path:portal/data/dev/postgres#replication-password>"
    portalPassword: "<path:portal/data/dev/postgres#portal-password>"
    provisioningPassword: "<path:portal/data/dev/postgres#provisioning-password>"

pgadmin4:
  enabled: true
  secret:
    password: "<path:portal/data/dev/pgadmin4#password>"
  env:
    email: portal@catena-x.net
  existingSecret: secret-pgadmin4
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: portal-pgadmin4.dev.demo.catena-x.net
        paths:
        - path: /
          pathType: Prefix
    tls:
      - hosts:
        - portal-pgadmin4.dev.demo.catena-x.net
        secretName: tls-secret
