apiVersion: v1
kind: Secret
metadata:
  name: secret-pgadmin4
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.pgadmin4.secret.password | default ( randAlphaNum 32 | quote ) }}
