name: Portal Lint and Test Chart

on: 
  push:
    # paths:
    #   - 'charts/portal/**'
    branches: [fix/helm-test]
  pull_request:
    paths:
      - 'charts/portal/**'
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.9.3

      # Setup python as a prerequisite for chart linting 
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      # - name: Run chart-testing (list-changed)
      #   id: list-changed
      #   run: |
      #     changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
      #     if [[ -n "$changed" ]]; then
      #       echo "::set-output name=changed::true"
      #     fi

      # run chart linting 
      - name: Run chart-testing (lint)
        run: ct lint --all --config charts/chart-testing-config-helm-environments.yaml

      # Preparing a kind cluster to install and test charts on
      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        # if: steps.list-changed.outputs.changed == 'true'

      # install the chart to the kind cluster and run helm test
      # define charts to test with the --charts parameter
      - name: Run chart-testing (install)
        run: ct install --charts charts/portal --config charts/chart-testing-config-helm-environments.yaml
        # if: steps.list-changed.outputs.changed == 'true'
