name: Provisioning-Service Auto-image-update

on:
  workflow_dispatch:
    inputs:
      new-image:
        description: 'new available image'
        required: true
        default: 'no content'

env:
  IMAGE_BEGINN: 'provisioningservicetag: '
  IMAGE_FULL_NEW: 'provisioningservicetag: ${{ inputs.new-image }}'

jobs:
  update-image-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Modify image tag in values-dev.yaml
        run: |
          sed -i 's/${{ env.IMAGE_BEGINN }}.*/${{ env.IMAGE_FULL_NEW }}/' charts/portal/values-dev.yaml

      - name: Commit and push updated values-dev.yaml
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add charts/portal/values-dev.yaml
          git commit -m "Add new image for provisioning service"
          bash ./scripts/push.sh
